services:
  kafka:
    user: root
    build:
      dockerfile: ./Dockerfile
    privileged: true
    volumes:
      - ./data/home/syj:/home/syj
      - ./data/root:/root
      - kafka-data:/home/data
    ports:
      - '19092:9092'
      - '19093:9093'
volumes:
  kafka-data: